version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samoa-finance-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Database - Use your Supabase credentials
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      # NextAuth
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      # Node
      NODE_ENV: production
    volumes:
      # Persist uploaded files
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
